# Generated by Django 5.1.7 on 2025-03-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('todo', '0002_alter_todo_labels_alter_todo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
