# Generated by Django 5.1.7 on 2025-03-09 14:19

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Working'), (3, 'Completed')], default=1)),
                ('priority', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('started_on', models.DateTimeField(null=True)),
                ('completed_on', models.DateTimeField(null=True)),
                ('due_on', models.DateTimeField(null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('labels', models.ManyToManyField(null=True, to='todo.label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Cat'), (2, 'Dog')]), size=None)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='todo.todo')),
            ],
        ),
    ]
