# Generated by Django 5.1.7 on 2025-03-10 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_labels_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'cat'), (2, 'dog')]), size=None),
        ),
    ]
