# Generated by Django 5.1.7 on 2025-03-10 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_log_words'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.CheckConstraint(condition=models.Q(('completed_on__gt', models.F('started_on'))), name='completed_on_gt_started_on'),
        ),
    ]
