# Generated by Django 5.1.7 on 2025-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_completed_on_gt_started_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='logs',
            field=models.ManyToManyField(related_name='todos', to='todo.banwords'),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
